#!/usr/bin/env python3
"""AutoPoC — Proof of Concept Test Script for forkd

Generated by the PoC Execute agent. Tests the deployed forkd-controller service
according to the PoC plan.
"""

import json
import os
import sys
import time
import urllib.request
import urllib.error

# Configuration
SERVICE_URL = os.environ.get("SERVICE_URL", sys.argv[1] if len(sys.argv) > 1 else "")
MAX_RETRIES = 5
RETRY_DELAY = 10  # seconds

results = []


def test_scenario(name, description, method, path, body=None, expected_status=200,
                  expected_content=None, validate_fn=None, timeout=30):
    """Run a single test scenario."""
    url = f"{SERVICE_URL.rstrip('/')}{path}"
    start = time.time()

    for attempt in range(MAX_RETRIES):
        try:
            if body is not None:
                data = json.dumps(body).encode("utf-8") if isinstance(body, dict) else body.encode("utf-8")
                req = urllib.request.Request(url, data=data, method=method)
                req.add_header("Content-Type", "application/json")
            else:
                req = urllib.request.Request(url, method=method)

            with urllib.request.urlopen(req, timeout=timeout) as resp:
                status = resp.status
                response_body = resp.read().decode("utf-8")

                if isinstance(expected_status, (list, tuple)):
                    status_ok = status in expected_status
                else:
                    status_ok = status == expected_status

                if status_ok:
                    if validate_fn:
                        ok, msg = validate_fn(status, response_body)
                        result = {
                            "scenario_name": name,
                            "status": "pass" if ok else "fail",
                            "output": response_body[:2000],
                            "error_message": None if ok else msg,
                            "duration_seconds": round(time.time() - start, 2),
                        }
                    elif expected_content and expected_content not in response_body:
                        result = {
                            "scenario_name": name,
                            "status": "fail",
                            "output": response_body[:2000],
                            "error_message": f"Expected content '{expected_content}' not found in response",
                            "duration_seconds": round(time.time() - start, 2),
                        }
                    else:
                        result = {
                            "scenario_name": name,
                            "status": "pass",
                            "output": response_body[:2000],
                            "error_message": None,
                            "duration_seconds": round(time.time() - start, 2),
                        }
                    results.append(result)
                    return result
                else:
                    if attempt < MAX_RETRIES - 1:
                        time.sleep(RETRY_DELAY)
                        continue
                    result = {
                        "scenario_name": name,
                        "status": "fail",
                        "output": response_body[:2000],
                        "error_message": f"Expected status {expected_status}, got {status}",
                        "duration_seconds": round(time.time() - start, 2),
                    }
                    results.append(result)
                    return result

        except urllib.error.HTTPError as e:
            # HTTPError is a subclass of URLError; handle it first for status-code checks
            error_body = ""
            try:
                error_body = e.read().decode("utf-8")
            except Exception:
                pass

            if isinstance(expected_status, (list, tuple)):
                status_ok = e.code in expected_status
            else:
                status_ok = e.code == expected_status

            if status_ok:
                if validate_fn:
                    ok, msg = validate_fn(e.code, error_body)
                    result = {
                        "scenario_name": name,
                        "status": "pass" if ok else "fail",
                        "output": error_body[:2000],
                        "error_message": None if ok else msg,
                        "duration_seconds": round(time.time() - start, 2),
                    }
                else:
                    result = {
                        "scenario_name": name,
                        "status": "pass",
                        "output": error_body[:2000],
                        "error_message": None,
                        "duration_seconds": round(time.time() - start, 2),
                    }
                results.append(result)
                return result
            else:
                if attempt < MAX_RETRIES - 1:
                    print(f"  [{name}] Attempt {attempt + 1}/{MAX_RETRIES}: got HTTP {e.code}, expected {expected_status}. Retrying in {RETRY_DELAY}s...",
                          file=sys.stderr)
                    time.sleep(RETRY_DELAY)
                else:
                    result = {
                        "scenario_name": name,
                        "status": "fail",
                        "output": error_body[:2000],
                        "error_message": f"Expected status {expected_status}, got {e.code}",
                        "duration_seconds": round(time.time() - start, 2),
                    }
                    results.append(result)
                    return result

        except urllib.error.URLError as e:
            if attempt < MAX_RETRIES - 1:
                print(f"  [{name}] Attempt {attempt + 1}/{MAX_RETRIES} failed: {e}. Retrying in {RETRY_DELAY}s...",
                      file=sys.stderr)
                time.sleep(RETRY_DELAY)
            else:
                result = {
                    "scenario_name": name,
                    "status": "error",
                    "output": "",
                    "error_message": f"Service unreachable after {MAX_RETRIES} attempts: {e}",
                    "duration_seconds": round(time.time() - start, 2),
                }
                results.append(result)
                return result

        except Exception as e:
            result = {
                "scenario_name": name,
                "status": "error",
                "output": "",
                "error_message": str(e),
                "duration_seconds": round(time.time() - start, 2),
            }
            results.append(result)
            return result


# ========== TEST SCENARIOS ==========

# --- Scenario 1: health-check ---
def validate_sandboxes_list(status, body):
    """Validate that the response is a JSON array."""
    try:
        data = json.loads(body)
        if isinstance(data, list):
            return True, None
        return False, f"Expected JSON array, got {type(data).__name__}: {body[:500]}"
    except json.JSONDecodeError as e:
        return False, f"Response is not valid JSON: {e}"

test_scenario(
    name="health-check",
    description="Verify the forkd-controller HTTP server is running by listing sandboxes",
    method="GET",
    path="/v1/sandboxes",
    expected_status=200,
    validate_fn=validate_sandboxes_list,
    timeout=60,
)

# --- Scenario 2: list-snapshots ---
def validate_snapshots_list(status, body):
    """Validate that the response is a JSON array."""
    try:
        data = json.loads(body)
        if isinstance(data, list):
            return True, None
        return False, f"Expected JSON array, got {type(data).__name__}: {body[:500]}"
    except json.JSONDecodeError as e:
        return False, f"Response is not valid JSON: {e}"

test_scenario(
    name="list-snapshots",
    description="Verify the snapshots listing endpoint responds correctly",
    method="GET",
    path="/v1/snapshots",
    expected_status=200,
    validate_fn=validate_snapshots_list,
    timeout=15,
)

# --- Scenario 3: invalid-sandbox-request ---
def validate_404_error(status, body):
    """Validate that we get a proper error response for a non-existent sandbox."""
    if status != 404:
        return False, f"Expected 404, got {status}"
    # Check that response is valid JSON (error body)
    try:
        data = json.loads(body)
        return True, None
    except json.JSONDecodeError:
        # Even if not JSON, a 404 is still correct behavior
        return True, None

test_scenario(
    name="invalid-sandbox-request",
    description="GET a non-existent sandbox to verify error handling returns 404",
    method="GET",
    path="/v1/sandboxes/nonexistent-id",
    expected_status=404,
    validate_fn=validate_404_error,
    timeout=15,
)

# --- Scenario 4: create-sandbox-no-kvm ---
def validate_create_error(status, body):
    """Validate that sandbox creation fails gracefully without KVM."""
    # We accept any 4xx or 5xx as valid since KVM is not available
    if 400 <= status < 600:
        # Check that we got some response body (not a crash/empty response)
        if len(body.strip()) > 0:
            return True, None
        else:
            return False, "Empty error response body - controller might have crashed"
    return False, f"Expected 4xx or 5xx, got {status}"

test_scenario(
    name="create-sandbox-no-kvm",
    description="Attempt POST to create sandbox without KVM; should fail gracefully",
    method="POST",
    path="/v1/sandboxes",
    body={"snapshot": "test", "id": "poc-test"},
    expected_status=list(range(400, 600)),
    validate_fn=validate_create_error,
    timeout=30,
)

# After scenario 4, verify the controller is still alive by hitting health endpoint again
test_scenario(
    name="post-create-health-check",
    description="Verify controller is still healthy after failed sandbox creation (did not crash)",
    method="GET",
    path="/v1/sandboxes",
    expected_status=200,
    validate_fn=validate_sandboxes_list,
    timeout=15,
)

# ========== END SCENARIOS ==========

# Output results as JSON
print(json.dumps({"results": results}, indent=2))

# Exit with appropriate code
failed = any(r["status"] in ("fail", "error") for r in results)
sys.exit(1 if failed else 0)
